"""
Django settings for joscoonline project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1200
SESSION_COOKIE_SECURE = False  # Set to True for HTTPS-only cookies
SESSION_SAVE_EVERY_REQUEST = True  # Reset session expiry on each user action

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uj6kvopn3i92venue86bnt4s==nq6*5oj(o$t1$03*+-5-mk0d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles','joscoonline_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'joscoonline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'joscoonline.wsgi.application'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
MEDIA_ROOT=os.path.join(BASE_DIR),"media"
LOGIN_URL='login'
LOGIN_REDIRECT_URL = '/home/'  # Redirect after successful login

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL database engine
        'NAME': 'josco',                      # Replace with your database name
        'USER': 'joscodbadmin',               # Replace with your MySQL username
        'PASSWORD': 'OIrLoW1ETcXwQHpbmCtD',   # Replace with your MySQL password
        'HOST': 'josco-production-db-01.cfkcgxgxrps8.ap-south-1.rds.amazonaws.com',  # Database host
        'PORT': '3306',                       # Default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  # Enforce strict mode
        },
    },
    '46': {
        # 'ENGINE': 'MSSQL',     # Correct MSSQL backend for Django
        'ENGINE': 'sql_server.pyodbc',  # Engine for MSSQL
        'NAME': 'SCMJOSJMSBR25',              # Your MSSQL database name
        'USER': 'scmjosco',                        # MSSQL username
        'PASSWORD': 'INDSOFTJMS_DATA',                      # MSSQL password
        'HOST': '192.168.18.2',              # MSSQL server address
        'PORT': '1433',                      # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
            'extra_params': 'TrustServerCertificate=yes',  # Optional, to avoid certificate errors if needed
        },
    },

    '10': {
        'ENGINE': 'sql_server.pyodbc',#orrect MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR8',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.13.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
            'extra_params': 'TrustServerCertificate=yes',  # Optional, to avoid certificate errors if needed
        },
    },

    '49': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR29',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.6.153',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            # Ensure driver is installed
        },
    },
    '52': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR32',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.14.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '53': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR33',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.12.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '54': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR34',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.9.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '55': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR35',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.7.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '58': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR37',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.8.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '60': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR39',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.3.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '61': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR40',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.21.101',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '62': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR41',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.16.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '63': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR42',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.26.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '64': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR43',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.27.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '65': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR44',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.28.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '66': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR45',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.29.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '67': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR46',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.31.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '68': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR47',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.5.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '4': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR1',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.2.11',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '5': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR2',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.4.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },
    '9': {
        'ENGINE': 'mssql',  # Correct MSSQL backend for Django
        'NAME': 'SCMJOSJMSBR7',  # Your MSSQL database name
        'USER': 'sa',  # MSSQL username
        'PASSWORD': '',  # MSSQL password
        'HOST': '192.168.11.2',  # MSSQL server address
        'PORT': '1433',  # MSSQL port
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure driver is installed
        },
    },


}

AUTH_USER_MODEL = 'joscoonline_app.CustomUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL='/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
